name: My Workflow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.1 # Actualiza a la última versión que utiliza Node.js 16
      - uses: actions/setup-node@v2.4.0 # Actualiza a la última versión que utiliza Node.js 16
      - run: npm install
      - run: npm run build
      - run: npm test


